version: "3.9"

services: 
  db:
    image: postgres
    restart: always
    volumes:
      - .data/db:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_NAME=${DATABASE_NAME}"
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
  web:
    build: .
    command: make run
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db