"""
Django settings for technical_assignment project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/

development.py settings file contains all settings for a development environment.

"""

from .base import * # import all base settings.


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# TEST 
TEST_DB = {
    'NAME': env("TEST_DATABASE_NAME"),
}


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env("DATABASE_NAME"),
        'USER': env("DATABASE_USER"),
        'PASSWORD': env("DATABASE_PASSWORD"),
        'HOST': env("DATABASE_HOST"),
        'PORT': env("DATABASE_PORT"),
        'TEST': TEST_DB
    }
}